### PR TITLE
Create board screen, closes #32

### LINKED ISSUE #32: Create game board with initial state

### PR DESCRIPTION
**Pull request by daniellecalmon**

### CODE REVIEW

**Comment by daniellecalmon** [comment]
closes #32

**Comment by axross** [comment]
@EriMiwa @SyllindaCardoso 

Could you review these changes? The purpose of a code review is:

- Make sure what changes will be merged
- Ask Dani what you are not sure in the changes (reasons, intentions, and something like that)
- Discuss if you have any better idea in something in the code

**Comment by SyllindaCardoso** [comment]
Sorry guys!! I am still trying to open it!

**Comment by EriMiwa** [comment]
@danismgomes thanks for your great job! I checked your code then, it looks no problem so far. (because of lacking my knowledge, I can't give you better ideas. but understanding your code is my best way to learn Java...^^; )

**Review by EriMiwa — APPROVED** [review]
Thanks for programming! I think it is no problem for merging them.

**Review by SyllindaCardoso — APPROVED** [review]
It looks great! you can close this issue!
Thank you so much!!

**Pull request merged**
