### PR TITLE
Buttons states

### LINKED ISSUE #34: Implement clicking and changing buttons
When buttons are clicked, they have to change of state. Unless it is a Bone.
States:
Empty
Dog
Grass

### PR DESCRIPTION
**Pull request by daniellecalmon**
Closes #34

### CODE REVIEW

**Comment by daniellecalmon** [comment]
Could anyone take a look at my code and see if it is ok to merge?

**Comment by daniellecalmon** [comment]
DependsOn #33

**Review by EriMiwa — DISMISSED** [review]
OK! it gonna be no problem for me! thanks!! :)

**Review by EriMiwa — APPROVED** [review]

**Comment by daniellecalmon** [comment]
@EriMiwa Thank you!

**Pull request merged**
